# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.7.0-26.2
maven_group=savage.commoneconomy
archives_base_name=savs-common-economy

# Dependencies
fabric_api_version=0.152.2+26.2
caffeine_version=3.1.8
hikaricp_version=6.2.1
lettuce_version=6.3.2.RELEASE
permission_api_version=0.6.1
mariadb_version=3.5.7
postgresql_version=42.7.5
sqlite_version=3.45.3.0